name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - main
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          if [[ ${{ github.event.workflow_run.head_branch }} == 'main' ]]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          elif [[ ${{ github.event.workflow_run.head_branch }} == 'dev' ]]; then
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --alias=dev-myapp.vercel.app
          elif [[ ${{ github.event.workflow_run.head_branch }} == 'test' ]]; then
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --alias=test-myapp.vercel.app
          fi

      - name: Debug Information
        if: failure()
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Run Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"